# Generated by Django 5.2.4 on 2025-08-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BookingDate',
            new_name='bookingDate',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='No_of_guests',
            new_name='noOfGuests',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Inventory',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Title',
            new_name='title',
        ),
    ]
